

compile: core.cpp NodeGen.cpp definition.h attackChecker.cpp test.cpp evaluation.cpp Search.h Search.cpp hash.h hashTable.cpp MoveNode.h Board.h capGen.cpp uciPro.cpp uciPro.h timeRecord.h
	g++ -std=c++11 core.cpp board.cpp NodeGen.cpp evaluation.cpp attackChecker.cpp uciPro.cpp gameStart.cpp test.cpp hashTable.cpp Search.cpp capGen.cpp -w -o chessproj -O3

